apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-k8s.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: lms
  name: lms
spec:
  ports:
  - name: "18000"
    port: 18000
    targetPort: 18000
  - name: "19876"
    port: 19876
    targetPort: 19876
  selector:
    io.kompose.service: lms
status:
  loadBalancer: {}
